[package]
name = "typestates"
version = "0.1.2-alpha"
authors = ["José Duarte <jmg.duarte@campus.fct.unl.pt>"]
edition = "2018"
description = "macro_rules! to build typestates"
readme = "README.md"
license-file = "LICENSE"
keywords = ["typestate"]
categories = ["development-tools"]
homepage = "https://github.com/rustype/typestates-rs"
repository = "https://github.com/rustype/typestates-rs"

[dependencies]
