[package]
name = "typestate"
version = "0.6.2"
edition = "2018"
authors = ["José Duarte <jmg.duarte@campus.fct.unl.pt>"]
description = "A proc macro DSL for typestates"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["typestate"]
categories = ["development-tools"]
homepage = "https://github.com/rustype/typestate-rs"
repository = "https://github.com/rustype/typestate-rs"
autotests = false

[features]
default = ["std"]
std = []
debug_dot = ["typestate-proc-macro/dot"]
debug_plantuml = ["typestate-proc-macro/plantuml"]
debug_mermaid = ["typestate-proc-macro/mermaid", "aquamarine"]

[dependencies]
typestate-proc-macro = { version = "0.6.2", path = "typestate-proc-macro", package = "typestate-proc-macro" }

aquamarine = { version = "0.1", optional = true }

[workspace]
members = ["typestate-automata", "typestate-proc-macro"]
